version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-{{ checksum "composer.json" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.json" }}

      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - ./

  test:
    docker:
      - image: circleci/php:7.2-cli

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: /home/circleci/repo
      - run:
          name: Unit Tests
          command: vendor/bin/phpunit -c test/unit/phpunit.xml --log-junit test/unit/_junit/junit.xml -d memory_limit=512M

      - store_test_results:
          path: test/unit/_junit

      - store_artifacts:
          path: test/unit/_coverage
          destination: TestCoverage

workflows:
  version: 2

  development:
    jobs:
      - build
      - test:
          requires:
            - build